### PR TITLE
Rename Jade to pug

### PR DESCRIPTION
**Pull request by SuriyaaKudoIsc**
Hi @jnordberg, :smiley:

I edit the **`package.json`** file. :pencil:

> Because of the npm error: **`"WARN deprecated jade@1.11.0: Jade has been renamed to pug, please install the latest version of pug instead of jade"`**
#### See
- http://npmjs.org/package/pug
- https://github.com/pugjs/pug

_Yours,_
[**Suriyaa Kudo**](https://github.com/SuriyaaKudoIsc) :octocat:

### CODE REVIEW

**Comment by jnordberg** [comment]
Hi, and thanks! Just had a look on npm and the only versions of pug are
```
     '0.0.0',
     '0.1.0',
     '2.0.0-alpha1',
     '2.0.0-alpha2',
     '2.0.0-alpha3'
```

Seems like this might be more than a rename..

**Comment by SuriyaaKudoIsc** [comment]
I changed the version to **`0.1.0`**.

It's better to use the stable version **`0.1.0`** instead of the alpha version:

```npm
'2.0.0-alpha1',
'2.0.0-alpha2',
'2.0.0-alpha3'
```

**Comment by jnordberg** [comment]
Agreed, but strange versions for just a name change, is there any documentation about it? Which version is equivalent to 1.11.0?

**Comment by SuriyaaKudoIsc** [comment]
If found it here: https://github.com/pugjs/pug/issues/2184! :smiley:

**Comment by timvandermeij** [comment]
Is anything blocking this PR? It would be nice to get rid of this warning.

**Comment by SuriyaaKudoIsc** [comment]
I'm also waiting for an answer from @jnordberg. :watch:

**Comment by jnordberg** [comment]
I'm waiting for a stable pug release, they are still in alpha afaik

**Comment by DamonGant** [comment]
Is this something that's still going to happen?

**Comment by jnordberg** [comment]
This will happen when they release a stable version

**Comment by SuriyaaKudoIsc** [comment]
@jnordberg New version available: [**`pug 1.11.0`**](https://github.com/pugjs/pug/releases/tag/1.11.0)!

**Comment by jnordberg** [comment]
The 1.x version is not on npm and the developers have stated that they won't publish it under the pug name. https://github.com/pugjs/pug/issues/2352

Looks like we will have to live with the deprecation warning until pug 2 is stable

**Comment by jnordberg** [comment]
I've forked jade 1.11 to [jade-legacy](https://github.com/jnordberg/jade-legacy) and will be maintaining that with security patches until the pug team releases something.

**Comment by SuriyaaKudoIsc** [comment]
@jnordberg Any changes?

**Comment by jnordberg** [comment]
Added in 2.5.0!

**Pull request closed without merging**
